Change implementation from .NET framework to .NET core 2.1
TotalJobsGroup/CandidateTest pull request #2
Opened 2018-11-01 13:25 UTC by umairdojki

2018-11-13 17:03 UTC, neilkennedy commented
@umairdojki can you rename the `QuestionServiceWebApi` project to be consistent with the other two. Something like `PairingTest.WebApi`. (Or rename the other two projects )

2018-11-13 17:05 UTC, neilkennedy commented on src/QuestionServiceWebApi/appsettings.json
> +  "AllowedHosts": "*"
Will this allow CORs requests from the web project in javascript?

2018-11-14 09:43 UTC, neilkennedy requested changes
See comments.

2018-11-18 20:59 UTC, yetanotherchris commented
It's nice to see your progress but unsubscribe me from this bloody thread! Argh

2018-11-22 18:27 UTC, umairdojki commented on src/QuestionServiceWebApi/appsettings.json
> +  "AllowedHosts": "*"
This was a default setting. It doesn't seem to have any effect on whether a CORS request is allowed or not. To enable CORS in the app, we will have to make some changes in Startup.cs, and in the Controller. See here: https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1 (Did follow these and managed to get it working).

2018-11-23 10:43 UTC, neilkennedy approved these changes

2018-11-23 10:44 UTC, merged